server:
  port: 8087

spring:
  application:
    name: seckill-product
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    cluster:
      nodes:
        - 192.168.56.102:6382
        - 192.168.56.102:6383
        - 192.168.56.102:6384
        - 192.168.56.103:6379
        - 192.168.56.103:6380
        - 192.168.56.103:6381
        - 192.168.56.104:6385
        - 192.168.56.104:6386
        - 192.168.56.104:6387
      max-redirects: 3
    lettuce:
      pool:
        max-active: 8
        max-wait: 1000ms
        max-idle: 0
    timeout: 10000ms
    password: passwd1234


mybatis:
  mapper-locations: classpath*:src/main/java/**/*Mapper.xml

logging:
  level:
    com.seckill.*: debug