server:
  port: 8084

spring:
  application:
    name: manager-merchant
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

mybatis:
  mapper-locations: classpath*:src/main/java/**/*Mapper.xml