server:
  port: 8082

spring:
  application:
    name: manager-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

logging:
  level:
    com.seckill.*: debug